// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PolicyOperations.Infrastructure.Persistence;

#nullable disable

namespace PolicyOperations.Infrastructure.Migrations;

[DbContext(typeof(PolicyOperationsDbContext))]
[Migration("20260228225832_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.24")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("PolicyOperations.Domain.Policies.Policy", entity =>
        {
            entity.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            entity.Property<decimal>("InsuredAmount")
                .HasColumnType("decimal(18,2)");

            entity.Property<bool>("IsActive")
                .HasColumnType("bit");

            entity.Property<DateTime>("IssueDate")
                .HasColumnType("datetime2");

            entity.Property<string>("PolicyNumber")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            entity.HasKey("Id");

            entity.ToTable("Policies");
        });
#pragma warning restore 612, 618
    }
}
