// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyOperations.Infrastructure.Persistence;

#nullable disable

namespace PolicyOperations.Infrastructure.Migrations
{
    [DbContext(typeof(PolicyOperationsDbContext))]
    [Migration("20260801213622_PolicyLifecycleFoundation")]
    partial class PolicyLifecycleFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyOperations.Domain.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal>("InsuredAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NormalizedPolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Policies_NormalizedPolicyNumber");

                    b.ToTable("Policies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Policies_InsuredAmount_Positive", "[InsuredAmount] > 0");

                            t.HasCheckConstraint("CK_Policies_Status_Valid", "[Status] IN (N'Draft', N'Active', N'Cancelled')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
