// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyOperations.Infrastructure.Persistence;

#nullable disable

namespace PolicyOperations.Infrastructure.Migrations
{
    [DbContext(typeof(PolicyOperationsDbContext))]
    [Migration("20260801221724_OrganizationLifecycleSecurity")]
    partial class OrganizationLifecycleSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyOperations.Domain.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("CoverageEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CoverageStartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("InsuredAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InsuredPartyReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedPolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("AK_Policies_OrganizationId_Id");

                    b.HasIndex("OrganizationId", "NormalizedPolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Policies_Organization_NormalizedPolicyNumber");

                    b.ToTable("Policies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Policies_ActivationData_Complete", "[Status] <> N'Active' OR ([InsuredPartyReference] IS NOT NULL AND [CoverageStartDate] IS NOT NULL AND [CoverageEndDate] IS NOT NULL AND [CoverageEndDate] >= [CoverageStartDate])");

                            t.HasCheckConstraint("CK_Policies_Currency_Format", "LEN([Currency]) = 3 AND [Currency] = UPPER([Currency]) AND [Currency] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^A-Z]%'");

                            t.HasCheckConstraint("CK_Policies_InsuredAmount_Positive", "[InsuredAmount] > 0");

                            t.HasCheckConstraint("CK_Policies_Status_Valid", "[Status] IN (N'Draft', N'Active', N'Cancelled')");
                        });
                });

            modelBuilder.Entity("PolicyOperations.Domain.Policies.PolicyTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "PolicyId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_PolicyTransitions_Organization_Policy_OccurredAtUtc");

                    b.ToTable("PolicyTransitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PolicyTransitions_Status_Valid", "[FromStatus] IN (N'Draft', N'Active') AND [ToStatus] IN (N'Active', N'Cancelled') AND [FromStatus] <> [ToStatus]");
                        });
                });

            modelBuilder.Entity("PolicyOperations.Domain.Policies.PolicyTransition", b =>
                {
                    b.HasOne("PolicyOperations.Domain.Policies.Policy", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PolicyId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
